### ISSUE TITLE
Issue 9:  Implement "self sizing cells" and "dynamic type" on table view

### ISSUE THREAD

**Issue by xoihin** [xoihin/ShakeToRecord#10]

**Comment by xoihin** [comment]
![selfsizingcells](https://cloud.githubusercontent.com/assets/13337141/10650984/bc594ad0-781a-11e5-9f8e-eba530bccb7c.png)

**Comment by xoihin** [comment]
...

**Comment by xoihin** [comment]
Self sizing cells.

**Comment by nerdyverde** [comment]
Resolved in #22
