### ISSUE TITLE
Issue 11:  In playback mode, pause audio when user presses home button.  When app launch again playback from where it was left off.

### ISSUE THREAD

**Issue by xoihin** [xoihin/ShakeToRecord#12]

**Comment by xoihin** [comment]
![playbackcontrols](https://cloud.githubusercontent.com/assets/13337141/10651011/daf083aa-781a-11e5-9b12-cbc559365141.png)

**Comment by xoihin** [comment]
...

**Comment by xoihin** [comment]
Hi Michael,

I changed this feature a bit on this issue.

Xoi

**Comment by nerdyverde** [comment]
Resolved in #22
