### ISSUE TITLE
Issue 0: List of audio files on table view

### ISSUE THREAD

**Issue by xoihin** [xoihin/ShakeToRecord#14]

**Comment by nerdyverde** [comment]
Please add a wireframe for this task showing how the list of audio files will be displayed in the app

**Comment by xoihin** [comment]
![userstory1-listallfiles](https://cloud.githubusercontent.com/assets/13337141/10652391/4ec859c0-7824-11e5-8025-91e2269afdfd.png)

**Comment by xoihin** [comment]
List of all audio files from document directory...
