### ISSUE TITLE
Add support for string localization

### ISSUE THREAD

**Issue by nerdyverde** [xoihin/ShakeToRecord#17]
There are a number of literal strings in the app that aren't wrapped in NSLocalizedString. Even if you don't have any immediate plans to support localization, it is a good practice to do this.

**Comment by xoihin** [comment]
This is a great suggestion,  I will include it on the next feature branch.

**Comment by nerdyverde** [comment]
Resolved in the [PR for user story 6](https://github.com/xoihin/ShakeToRecord/pull/16)
