### ISSUE TITLE
Issue 2:  Start.stop recording when devices is shaken

### ISSUE THREAD

**Issue by xoihin** [xoihin/ShakeToRecord#2]

**Comment by xoihin** [comment]
![playbackcontrols](https://cloud.githubusercontent.com/assets/13337141/10650938/6ce63e54-781a-11e5-8ff0-bcdff2dcd05e.png)

**Comment by nerdyverde** [comment]
In addition to this wireframe, could you add one that shows what the recording state and/or transition to recording state looks like?

**Comment by xoihin** [comment]
![issue 2 - prepare to record](https://cloud.githubusercontent.com/assets/13337141/10652610/144d7102-7826-11e5-84cf-1d0c526f91b4.png)

**Comment by xoihin** [comment]
Prepare to record.

**Comment by xoihin** [comment]
![issue 2 - user shaked - about to record](https://cloud.githubusercontent.com/assets/13337141/10652627/25f3d8a6-7826-11e5-91bf-2923e9aae88e.png)

**Comment by xoihin** [comment]
Shake detected - Countdown to record.

**Comment by xoihin** [comment]
![issue 2 - recording saved](https://cloud.githubusercontent.com/assets/13337141/10652640/43c84b0a-7826-11e5-906f-ab9f6be368cd.png)

**Comment by xoihin** [comment]
New recording saved.
