### ISSUE TITLE
Issue 14:  Add "Share" feature to send audio files using Airdrop, email, or iMessage.

### ISSUE THREAD

**Issue by xoihin** [xoihin/ShakeToRecord#20]

**Comment by xoihin** [comment]
Add "Share" feature to send audio files by Airdrop, email, or iMessage.

**Comment by xoihin** [comment]
Hi Michael,

Thanks for the suggestion.  I changed this feature to also include sending by email and iMessage.

Xoi

**Comment by nerdyverde** [comment]
Resolved in #22
