### ISSUE TITLE
Issue 5:  Implement playback feature on audio files

### ISSUE THREAD

**Issue by xoihin** [xoihin/ShakeToRecord#6]

**Comment by nerdyverde** [comment]
Please add a wireframe here demonstrating what the UI would look like. Comments describing the UX flow would be helpful too.

**Comment by xoihin** [comment]
![playbackcontrols](https://cloud.githubusercontent.com/assets/13337141/10650955/878c1a12-781a-11e5-8c68-19ded80d931d.png)

**Comment by xoihin** [comment]
...

**Comment by xoihin** [comment]
![playing audio](https://cloud.githubusercontent.com/assets/13337141/10652805/7550be54-7827-11e5-9533-38d39930543d.png)

**Comment by xoihin** [comment]
Screen is showing the audio file is playing.  Play button is disabled and pause and stop button are enabled.

**Comment by xoihin** [comment]
![pausing](https://cloud.githubusercontent.com/assets/13337141/10652824/a5b36646-7827-11e5-803f-153d32253c36.png)

**Comment by xoihin** [comment]
Paused while an audio file is playing.
