### ISSUE TITLE
Issue 6:  Implement delete and rename of audio files

### ISSUE THREAD

**Issue by xoihin** [xoihin/ShakeToRecord#7]

**Comment by nerdyverde** [comment]
Please add wireframes demonstrating the UI for this task. Are buttons displayed in a given row on a swipe (like in Mail.app, for example)? What UI is displayed when renaming a row?

**Comment by xoihin** [comment]
![delete rename share](https://cloud.githubusercontent.com/assets/13337141/10652851/e72d9a42-7827-11e5-85c4-f49c384014e7.png)

**Comment by xoihin** [comment]
Swipe cell from right.  There will be "delete" and "more" options.

**Comment by xoihin** [comment]
![swipe to reveal delete and rename](https://cloud.githubusercontent.com/assets/13337141/10652991/0918b5aa-7829-11e5-897a-21fa5506ade2.png)

**Comment by xoihin** [comment]
Swipe to delete and to rename (more).

**Comment by xoihin** [comment]
![rename](https://cloud.githubusercontent.com/assets/13337141/10652999/2077e4f0-7829-11e5-9401-10c94cf8ef23.png)

**Comment by xoihin** [comment]
Rename.

**Comment by xoihin** [comment]
![enter new file name](https://cloud.githubusercontent.com/assets/13337141/10653004/2f3b47b6-7829-11e5-9167-bc7778ef97dd.png)

**Comment by xoihin** [comment]
New File name.
