### ISSUE TITLE
Issue 7: Implement search audio feature

### ISSUE THREAD

**Issue by xoihin** [xoihin/ShakeToRecord#8]

**Comment by xoihin** [comment]
![search](https://cloud.githubusercontent.com/assets/13337141/10650971/995b23c8-781a-11e5-9b54-6a412ab21b37.png)

**Comment by xoihin** [comment]
..

**Comment by xoihin** [comment]
added wireframe

**Comment by nerdyverde** [comment]
Resolved in #22
